
#ifndef ROPUFU_SEQUENTIAL_INTERMITTENT_CONFIG_HPP_INCLUDED
#define ROPUFU_SEQUENTIAL_INTERMITTENT_CONFIG_HPP_INCLUDED

#include "config.g.hpp"

#endif // ROPUFU_SEQUENTIAL_INTERMITTENT_LLR_TRANSFORM_HPP_INCLUDED
